import json
from datetime import datetime

from utils.config import COMPLIANCE_REPORT_PATH, DRIFT_REPORT_PATH, REPORT_MD_PATH
from utils.logging_utils import setup_logger

logger = setup_logger(__name__)


def write_report(
    validation_report: dict,
    performance_report: dict,
    report_path=REPORT_MD_PATH,
) -> str:
    compliance = {}
    drift = {}

    if COMPLIANCE_REPORT_PATH.exists():
        with open(COMPLIANCE_REPORT_PATH, "r", encoding="utf-8") as f:
            compliance = json.load(f)

    if DRIFT_REPORT_PATH.exists():
        with open(DRIFT_REPORT_PATH, "r", encoding="utf-8") as f:
            drift = json.load(f)

    report_path_obj = (
        report_path if hasattr(report_path, "mkdir") else __import__("pathlib").Path(report_path)
    )
    report_path_obj.parent.mkdir(parents=True, exist_ok=True)

    with open(str(report_path_obj), "w", encoding="utf-8") as f:
        f.write(f"# AgentX Model Validation Report\n\n")
        f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}  \n\n")

        f.write("## Data Validation Summary\n")
        for key, value in validation_report.items():
            f.write(f"- **{key.replace('_', ' ').title()}**: {value}\n")
        f.write("\n")

        f.write("## Model Performance Metrics\n")
        for key, value in performance_report.items():
            try:
                val = round(float(value), 4)
            except Exception:
                val = value
            f.write(f"- **{key.replace('_', ' ').title()}**: {val}\n")
        f.write("\n")

        if compliance:
            f.write("## Compliance Summary\n")
            answer = compliance.get("answer") or compliance.get("content") or ""
            if answer:
                f.write(f"**Response:**\n{answer}\n\n")

        if drift:
            f.write("## Drift Detection Summary\n")
            f.write(f"- **Drift Detected:** {drift.get('drift_detected', False)}\n\n")
            details = drift.get("details", [])
            drifted_features = [d for d in details if d.get("drifted")]
            if drifted_features:
                f.write("### Drifted Features:\n")
                for item in drifted_features:
                    f.write(f"- {item.get('feature')} (p-value: {item.get('p_value')})\n")
                f.write("\n")

        f.write("---\n")
        f.write("*Report generated by AgentX.*\n")

    logger.info("Validation report saved to %s", report_path_obj)
    return str(report_path_obj)
